local addon = require("addon-builder"):Build()

describe("PmqCore", function()
  local logSpy = spy.on(addon.Logger, "Log")

  before_each(function()
    addon.Logger.Log:clear()
  end)

  describe("addon:catch", function()
    it("can catch errors", function()
      assert.has_no_error(function()
        addon:catch(function() error("Intentional error") end)
      end)
    end)
    it("can log errors", function()
      addon:catch(function() error("Intentional error") end)
      assert.spy(logSpy).was_called()
    end)
    it("does not log if no error occurred", function()
      addon:catch(function() end)
      assert.spy(logSpy).was_not_called()
    end)
  end)
end)
