--- This is the default addon config for every addon built with addon-builder
return {
  CHARSET = "ANSI",
  ENABLE_GUI = false,
  ENABLE_SELF_MESSAGING = true,
  ENABLE_TRANSACTION_LOGS = false,
  FEATURE_PET_KILLS = true,
  FILTER_OFFLINE_MESSAGE = true,
  GLOBAL_LOG_FILTER = "fatal",
  ITEM_SCAN_LOG_INTERVAL = 500,
  ITEM_SCAN_TIMEOUT = 1,
  NOTIFY_COMPLETE_AUTHOR = true,
  NOTIFY_COMPLETE_SHARER = true,
  NOTIFY_COMPLETE_BULK = true,
  NOTIFY_VERSION_UPDATE = true,
  PLAYER_LOCATION_INTERVAL = 1.0,
  PLAYER_LOCATION_TTL = 0,
  SPELL_SCAN_INTENSITY = 5,
  SPELL_SCAN_LOG_INTERVAL = 5000,
  URL_DISCORD = "https://discord.gg/abcdefg",
  URL_GITHUB = "https://github.com/runeberry/PlayerMadeQuests",
  URL_WIKI = "https://pmq.runeberry.com",
  START_MENU = "",
  VERSION_INFO_TTL = 1,

  Logging = {},
  FrameData = {},
}